### PR TITLE
Feature mission fsm

### PR DESCRIPTION
**Pull request by jtoppins**
This is the initial stage of the mission class rewrite.

This series implements a FSM inside the Mission class. The defined states are:
 * preparing
 * active
 * complete
 * timeout

These states combined with a plan of actions allow for a more generic mission infrastructure. The active state executes the plan and upon completion of the plan the mission is a success.

### CODE REVIEW

**Comment by wheelyjoe** [comment]
What testing needs to be done for this? Are basic missions (ie as they exist in the old system) supported?

**Comment by jtoppins** [comment]
Things that need to be tested is basically verification that all the old mission functionality works sans checkin and checkout those are broken an should generate tracebacks.

**Comment by wheelyjoe** [comment]
Gotcha, can do later

**Comment by Kijaxu** [comment]
I have tested this now, all pre-existing functionality seems intact, no errors or issues.

**Pull request merged**
